services:
  torchserve:
    build: .
    restart: always
    volumes:
      - "./model-store:/code/model-store"
      - "./save_model:/code/save_model"
    ports:
      - "9090:8080"
      - "9091:8081"
      - "9092:8082"